[Coin Top]
name = "solana-verifiable-build"
version = "0.1.0"
description = "Agriculture Based Carbon Credit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]
