name: Publish All Changed Images

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to compare from'
        required: true
        type: string


jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=d ${{ github.event.inputs.commit_hash }} ${{ github.sha }} | grep '^docker/v.*\.Dockerfile$' || true)
          echo "CHANGED_FILE=$CHANGED_FILES"
          if [ -n "$CHANGED_FILES" ]; then
            echo "$(echo "$CHANGED_FILES" | jq -R -s 'split("\n") | map(select(length > 0)) | map(.[8:-11])' | tr -d '[:space:]')"
            echo "versions=$(echo "$CHANGED_FILES" | jq -R -s 'split("\n") | map(select(length > 0)) | map(.[8:-11])' | tr -d '[:space:]')" >> $GITHUB_OUTPUT
          else
            echo "versions=[]" >> $GITHUB_OUTPUT
          fi
          echo $GITHUB_OUTPUT
      - name: Display matrix
        run: echo "${{ steps.set-matrix.outputs.versions }}"

  push_to_registries:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.versions != '[]' }}
    strategy:
      fail-fast: false
      matrix: 
        version: ${{ fromJson(needs.detect_changes.outputs.versions )}}
    name: Push Docker images to docker.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Report version
        run: echo "Pushing Docker image for version ${{ matrix.version }}"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
             docker.io/solanafoundation/solana-verifiable-build

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: docker/
          file: docker/v${{ matrix.version }}.Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            docker.io/solanafoundation/solana-verifiable-build:${{ matrix.version }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/solanafoundation/solana-verifiable-build
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
